-- Zero-cost, provider-neutral Gmail Watch state.
--
-- Only the service role may read/write these tables.  Gmail message bodies,
-- attachments and sender addresses are never stored here; the message tables
-- contain bounded parser metadata and the public-safe projection only.
create table if not exists public.gmail_watch_state (
  id text primary key check (id = 'primary'),
  watch_expiration timestamptz,
  watch_last_renewed_at timestamptz,
  watch_error text,
  watch_error_at timestamptz,
  last_history_id text,
  pending_history_id text,
  last_notification_at timestamptz,
  last_sync_at timestamptz,
  last_full_sync_at timestamptz,
  last_message_id text,
  updated_at timestamptz not null default now()
);

create table if not exists public.gmail_email_observations (
  gmail_message_id text primary key,
  observation_id text not null,
  content_hash text,
  creator_episode_key text,
  event_cluster_key text,
  parse_status text not null,
  parser_version text not null,
  received_at timestamptz,
  inserted_at timestamptz not null default now(),
  metadata_json jsonb not null default '{}'::jsonb
);

create unique index if not exists gmail_email_observations_content_hash_idx
  on public.gmail_email_observations (content_hash)
  where content_hash is not null;

create table if not exists public.gmail_email_dlq (
  id bigint generated by default as identity primary key,
  gmail_message_id text not null,
  parser_name text not null,
  parser_version text not null,
  template_fingerprint text not null,
  parse_status text not null,
  failure_reason text not null,
  created_at timestamptz not null default now(),
  metadata_json jsonb not null default '{}'::jsonb
);

create table if not exists public.gmail_public_observations (
  observation_id text primary key,
  content_origin text not null,
  content_hash text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  payload_json jsonb not null
);

create index if not exists gmail_public_observations_created_idx
  on public.gmail_public_observations (created_at desc, observation_id desc);

create table if not exists public.gmail_pubsub_events (
  history_id text primary key,
  gmail_address_hash text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  dispatch_status text not null default 'pending' check (dispatch_status in ('pending', 'dispatched', 'failed')),
  dispatch_error text
);

alter table public.gmail_watch_state enable row level security;
alter table public.gmail_email_observations enable row level security;
alter table public.gmail_email_dlq enable row level security;
alter table public.gmail_public_observations enable row level security;
alter table public.gmail_pubsub_events enable row level security;

comment on table public.gmail_watch_state is
  'Private singleton Gmail Watch lease/cursor. Service role only; no raw mail.';
comment on table public.gmail_public_observations is
  'Reviewed public-safe Creator/FJ projection; raw Gmail content is prohibited.';
comment on table public.gmail_pubsub_events is
  'Idempotent Gmail Pub/Sub notification cursors; address is stored only as a hash.';
